# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "About"
  url = "/#about"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

# -- Footer Menu --

[[footer]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 20
